dist: xenial
language: python
python:
  - "3.8"

services:
  - docker

addons:
  snaps:
    - name: helm
      classic: true

env:
  global:
    - HELM_EXPERIMENTAL_OCI=1
    - REPOSITORY=${DOCKER_HOSTNAME}/${DOCKER_NAMESPACE}/arrow-flight-module
    - HELM_REPOSITORY=${REPOSITORY}-chart
    - TAG=0.0.0
    
install:
  - pip install pipenv
  - pipenv install

script:
  - make test
  - make helm-verify
  - make build

deploy:
  provider: script
  script: >-
    sudo chmod o+x /etc/docker &&
    docker login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN} ${DOCKER_HOSTNAME} &&
    helm registry login -u ${DOCKER_USERNAME} -p ${DOCKER_TOKEN} ${DOCKER_HOSTNAME} &&
    make push chart-push
  on:
    branch: tagRelease
