app-uuid: {{ .Values.uuid | default "app-uuid-missing" }}
{{ if .Values.assets -}}
data:
{{- range .Values.assets }}
  - format: {{ .source.format }}
    name: {{ .assetID | quote }}
    capability: {{ .capability }}
    {{- if index .source "connection" "fybrik-arrow-flight" }}
    connection:
      type: flight
      flight:
        endpoint_url: {{ index .source "connection" "fybrik-arrow-flight" "hostname" }}
        port: {{ index .source "connection" "fybrik-arrow-flight" "port" }}
        flight_command: "{ \"asset\": \"{{ .assetID }}\" }"
    {{- end }}
    {{- if .source.connection.s3 }}
    path: "{{ .source.connection.s3.bucket }}/{{ .source.connection.s3.object_key }}"
    connection:
      type: s3
      s3:
        endpoint_url: {{if not (contains "://" .source.connection.s3.endpoint)}}https://{{end}}{{ .source.connection.s3.endpoint }}
        {{- range $k, $v := .source.vault }}
        {{- if eq $k "read" }}
        vault_credentials:
          {{- if $v.address }}
          address: {{ $v.address }}
          {{- end }}
          {{- if $v.authPath }}
          authPath: {{ $v.authPath }}
          {{- end }}
          {{- if $v.role }}
          role: {{ $v.role }}
          {{- end }}
          {{- if $v.secretPath }}
          secretPath: {{ $v.secretPath }}
          {{- end }}
          {{- end }}
        {{- end }}
    {{- end }}
    {{- if .transformations }}
    transformations:
    {{- $redactColumns := list -}}
    {{- $removeColumns := list -}}
    {{- range .transformations -}}
      {{- if eq .name "RedactAction" -}}
        {{- $redactColumns = .RedactAction.columns -}}
      {{- end -}}
      {{- if eq .name "RemoveAction" -}}
        {{- $removeColumns = .RemoveAction.columns -}}
      {{- end -}}
    {{- end -}}
    {{- if $redactColumns }}
      - action: "Redact"
        description: "redacting columns: {{ $redactColumns }}"
        columns: 
          {{- range $redactColumns}}
          - {{ . }}
          {{- end }}
        options:
          redactValue: "XXXXX"
    {{- end }}
    {{- if $removeColumns }}
      - action: "RemoveColumns"
        description: "removing columns: {{ $removeColumns }}"
        columns: 
          {{- range $removeColumns}}
          - {{ . }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end -}}
{{- else -}}
data: []
{{- end -}}
