# Try it with `helm install --generate-name --dry-run -f helm/afm/values.sample.yaml helm/afm`
metadata:
  labels: {}
  name: 012d42539692bba841a7
  namespace: default
read:
- assetID: "test1"
  source:
    connection:
      name: s3
      s3:
        bucket: fybrik-test-bucket
        endpoint: s3.eu-gb.cloud-object-storage.appdomain.cloud
        object_key: test1.parquet
      type: 2
    credentialLocation: htttp://test/test
    format: parquet
  transformations:
  - id: "redact-ID"
    level: 2 # column
    args:
      column_name: col1
  - id: "removed-ID"
    level: 2 # column
    args:
      column_name: col2
- assetID: "test2"
  source:
    connection:
      name: s3
      s3:
        bucket: fybrik-test-bucket
        endpoint: s3.eu-gb.cloud-object-storage.appdomain.cloud
        object_key: test2.parquet
      type: 2
    credentialLocation: htttp://test/test
    format: parquet
  transformations:
  - id: "redact-ID"
    level: 2 # column
    args:
      column_name: col1
